t1 = (91, 2, 3, 4, 5)
t2 = ("hello", "world")
# Tuples are immutable, so we cannot change elements
print("tuple t1:", t1)
print("tuple t2:", t2)
print("length of tuple t1:", len(t1))
print("length of tuple t2:", len(t2))
print("t1*2:", t1*2)
print(t1[0:3:2])
print("tuple after adding new element:", t2)
print(t1 + t2)
print("length of tuple t1:", len(t1))
print("length of tuple t2:", len(t2))
print("t1*2:", t1*2)
print(t1[0:3:2])
#tuple with single element
t3 = (1,)
print("tuple t3:", t3)
print("length of tuple t3:", len(t3))
